/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signupUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signinUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshAccessToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/check-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["checkEmailCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/item/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getItemByItemId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RequestCreateUserDTO: {
            name: string;
            email: string;
            password: string;
        };
        ResponseCreateUserDTO: {
            message: string;
        };
        RequestAuthenticateUserDTO: {
            email: string;
            password: string;
        };
        ResponseAuthenticateUserDTO: {
            access_token: string;
            refresh_token: string;
        };
        RequestRefreshAccessTokenDTO: {
            refresh_token: string;
        };
        ResponseRefreshAccessTokenDTO: {
            access_token: string;
            refresh_token: string;
        };
        RequestCheckCodeDTO: {
            email_code: string;
        };
        ResponseCheckEmailCodeDTO: {
            access_token: string;
            refresh_token: string;
        };
        ItemForGetItemsDTO: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            image_url: string;
            place_found: string;
            /** Format: date */
            date_found: string;
            is_claimed: boolean;
        };
        ResponseGetItemsDTO: {
            items: components["schemas"]["ItemForGetItemsDTO"][];
            /** Format: int64 */
            total_elements: number;
            /** Format: int32 */
            total_pages: number;
            /** Format: int32 */
            current_page: number;
        };
        ItemForGetItemByItemIdDTO: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            report: string;
            image_url: string;
            place_found: string;
            /** Format: date */
            date_found: string;
            place_stored: string;
            is_with_finder: boolean;
            is_claimed: boolean;
            /** Format: date */
            date_claimed: string;
        };
        ResponseGetItemByItemIdDTO: {
            item: components["schemas"]["ItemForGetItemByItemIdDTO"];
            user_finder: components["schemas"]["UserForGetItemByItemIdDTO"];
            user_claimer?: components["schemas"]["UserForGetItemByItemIdDTO"];
        };
        UserForGetItemByItemIdDTO: {
            /** Format: uuid */
            id: string;
            name: string;
            email: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signupUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCreateUserDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseCreateUserDTO"];
                };
            };
        };
    };
    signinUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestAuthenticateUserDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseAuthenticateUserDTO"];
                };
            };
        };
    };
    refreshAccessToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestRefreshAccessTokenDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseRefreshAccessTokenDTO"];
                };
            };
        };
    };
    checkEmailCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCheckCodeDTO"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseCheckEmailCodeDTO"];
                };
            };
        };
    };
    getItems: {
        parameters: {
            query: {
                page: number;
                size: number;
                search?: string;
                startDate?: string;
                endDate?: string;
                location?: string;
                addIsClaimed?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseGetItemsDTO"];
                };
            };
        };
    };
    getItemByItemId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseGetItemByItemIdDTO"];
                };
            };
        };
    };
}
